### PR TITLE
Fixed warnings found with gcc-10. Enabled Werror for CI builds.

### PR DESCRIPTION
**Pull request by klenze**

### CODE REVIEW

**Comment by klenze** [comment]
Should work now, fixes #716.

**Comment by klenze** [comment]
Motivation for this PR: People sometimes commit code which creates new warnings. About half the time, the warnings are actually due to bugs (such as && being used instead of &) or risky behavior (such as not initializing a pointer (with nullptr) which is supposed to be set in some loop). 

I am very convinced that we should have one test case for compilation with -Werror on at least one platform. It could be a separate test case perhaps. (If we compile with make instead of make -k and use -Wfatal-errors, and just print out the last 50 lines of the compilation output, finding the offending code would be easier.)

If the proposal #716 is rejected, I expect an alternative on how errors which are visible as warnings can reliably be caught and fixed.

**Comment by klenze** [comment]
> I think that the option "make" + "-Wfatal-errors" + "print out the last 50 lines" could be very useful.

Agreed. I will update my PR tomorrow. 

Ideally, we would also upload the full output to some web server so the user also gets useful feedback in case of very long warning messages (which may or may not exist. The error messages for templates are legendarily long).

**Comment by jose-luis-rs** [comment]
Hi

The file travis-generate-dockerfile.sh was deleted but this is still used by the hidden script ".travis.yml". Please, comment the line:
 - ${TRAVIS_BUILD_DIR}/travis-generate-dockerfile.sh | tee Dockerfile

Then I will see if we could add some specific tests to check other repositories like sofia, asyeos, glad, etc. This will help us to be sure everything is working properly.

Thanks in advance

**Comment by klenze** [comment]
see #729 for a sample failure. If anyone has a simpler way to output just the error, I am open to it. 

Also, I am kind of confused by the relationship between .travis.yml and .github/workflows/main.yml. 

From my understanding, the github CI replaced travis and the travis stuff is obsolete except for the travis-clang-format-check.sh which is called from the github CI. Am I wrong there?

**Comment by jose-luis-rs** [comment]
Hi, let me know when you finish with this PR to merge it. Thanks in advance

**Comment by klenze** [comment]
Hi,
I would say it is ready.
Cheers, 
   Philipp

**Comment by jose-luis-rs** [comment]
Ok, please, could you rebase the R3BRoot/dev branch?

**Pull request merged**
