### PR TITLE
Califa Energy Calibration

### PR DESCRIPTION
**Pull request by EliGaliana**
Modifying Califa Calibration classes and macros

Solving mistakes and adding libraries(Spectrum) to CMake

Improving the containerParameter

Including the class R3BCalifaMapped2CrystalCal

Solving problems and adding a new function to get parameters

Small modifications

Adding the checkResults.C and the energy smearing

Adding channel smearing

Adding channel smearing

### CODE REVIEW

**Comment by kresan** [comment]
Hi Eli,

Your commit has a broken test. Please discard the changes in r3bgen/testR3BPhaseSpaceGenerator.cxx and push again.

Cheers,
Dima

**Comment by EliGaliana** [comment]
Hi Dima,


I commented AddTrack function from r3bgen/testR3BPhaseSpaceGenerator.cxx because I couldn't compile R3B due to this error:


home/fpddv1/elisabet.galiana/Escritorio/R3BRoot/R3BRoot_source/r3bgen/testR3BPhaseSpaceGenerator.cxx:19:14: error: ‘void {anonymous}::MockFairPrimaryGenerator::AddTrack(Int_t, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t, Int_t, Bool_t, Double_t, Double_t, Double_t)’ marked ‘override’, but does not override
         void AddTrack(Int_t pdgid,

I'm going to discard this change and push my code again, but now I have the same error and I can't compile.

Cheers,
Eli




________________________________
De: Dmytro Kresan <notifications@github.com>
Enviado: martes, 16 de enero de 2018 11:14:05
Para: R3BRootGroup/R3BRoot
Cc: GALIANA BALDO ELISABET; Author
Asunto: Re: [R3BRootGroup/R3BRoot] Califa Energy Calibration (#182)


Hi Eli,

Your commit has a broken test. Please discard the changes in r3bgen/testR3BPhaseSpaceGenerator.cxx and push again.

Cheers,
Dima

**Comment by janmayer** [comment]
Hi Eli,

This is fixed already in the `dev` branch. You might try to rebase, see:
https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown#user-content-sync-your-feature-branch

Sorry for the inconveniences.
Jan

**Comment by EliGaliana** [comment]
Hi Jan,

I applyed the rebase (following the Anar steps) before to push my code, but it seems that failed. Today, I have tryed the rebase again, nothing changed and the code was up to date, so, I have to check where is the problem and why I can’t do the rebase properly.

Many thanks.
Eli


Obtén l'aplicació Outlook per a l'iOS<https://aka.ms/o0ukef>
_____________________________

**Pull request merged**
