### PR TITLE
Neuland1702

### PR DESCRIPTION
**Pull request by janmayer**
Neutron Cross Section Macros
Neutron Cross Section Results
Updated matrices macros
New PoorMansMultiProcessing using xargs
Updated matrix macros
Updated Neutron Cross Section Macros
More TH to Mc Mon and clusterfinder include guard
Moved and updated Clustering Code (ROOT6)
Digitizer got its own module (ROOT6)
Updated charged particle response macros
Updated tetraneutron macros
Updated Gitignore

### CODE REVIEW

**Comment by kresan** [comment]
Please remove "input" directory from main .gitignore file.

**Comment by janmayer** [comment]
I can do that if you want, however here is my reasoning:
The first thing after cloning the code is to get more input files, e.g. the Sn files from the r3broot homepage (which overwrites the short `128Sn_4n_600AMeV_500keV.dat` file) or by generating more. At that point running `git status` will constantly annoy you with the 20+ uncommitted files in `input/`.

**Comment by kresan** [comment]
ok, I agree. Will merge your request as it is.

**Comment by kresan** [comment]
please rebase

**Pull request merged**
