### PR TITLE
Updated classes for s091/s118 part1

### PR DESCRIPTION
**Pull request by ManuelXarepe**
Describe your proposal.

Part 1 of the RPC classes update for upcoming experiments.
Fixed a bug in mapped to precal.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed the [pull request guidlines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and the [Git workflow](https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown)
* [x] Followed the [seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Review by jose-luis-rs — CHANGES_REQUESTED** [review]
I have seen the problem with the online, this is because you have "spaces" in the name definition for all TFolder, TCanvas and histograms. Just introduce `_` to solve the problem. Example:
sprintf(name, "Left : Coarse Time Strip_%i", i + 1);
stripCoarseLeftHisto[i] = new TH1F(name, name, 200, 0, 2200);
---->
sprintf(name, "Left:Coarse_Time_Strip_%i", i + 1);
stripCoarseLeftHisto[i] = new TH1F(name, name, 200, 0, 2200);

**Comment by jose-luis-rs** [comment]
The definition of canvas is also inverted, you have for instance:
stripCalTimeCorrCanvas = new TCanvas("Left Time Vs Right Time", "leftTimeVsRightTime");

but it should be:
stripCalTimeCorrCanvas = new TCanvas("leftTimeVsRightTime", "Left Time Vs Right Time");
--->
new_canvas = new TCanvas("Name", "Title");

**Comment by jose-luis-rs** [comment]
You could also use:
`R3B::root_owned<TH2F>`  ; `R3B::root_owned<TH1F>` , .....
instead of
"new TH2F" ; "new TH1F" , .....

**Comment by ManuelXarepe** [comment]
> I have seen the problem with the online, this is because you have "spaces" in the name definition for all TFolder, TCanvas and histograms. Just introduce `_` to solve the problem. Example: sprintf(name, "Left : Coarse Time Strip_%i", i + 1); stripCoarseLeftHisto[i] = new TH1F(name, name, 200, 0, 2200); ----> sprintf(name, "Left:Coarse_Time_Strip_%i", i + 1); stripCoarseLeftHisto[i] = new TH1F(name, name, 200, 0, 2200);

Thank you for the help! I implemented this and changed TH1F and TH2F to r3b_owned... Now we see the cal level plots.
The number of lines changed skyrocketed but most of these are histogram names being changed, I believe it should be a easy review.

**Pull request merged**
