### PR TITLE
linker-fixes

### PR DESCRIPTION
**Pull request by miharenthas**
Hi, since a while I'm operating a custom branch of R3BRoot, which can be linked against executables (and also has a lot of other stuff in it which is relevant to me).
This pull-request is essentially a reasoned git cherry-pick of that branch to apply the fixes and enable GNU ld to link executables against all R3B libraries, leaving out other mods (irrelevant to this issue) and quite a bit of history clutter.

### CODE REVIEW

**Comment by janmayer** [comment]
Uhm, could you remove these huge comments? They are not needed at all - that's wat your commit message / this conversation is for.

**Comment by miharenthas** [comment]
Do you mean the comment boxes with the explanation of what the correction was about?

Sure, they were there for my personal utility (so I know what I did and why), left them in in case someone was curious.

**Comment by vadimr3b** [comment]
Please squash your commits.

**Comment by miharenthas** [comment]
Squashed. Please let me know if there are more fixes to do!

**Pull request merged**
