### PR TITLE
Renamed CalifaHit to CalifaCluster

### PR DESCRIPTION
**Pull request by jose-luis-rs**
Following #720

### CODE REVIEW

**Comment by ryotani** [comment]
What's the difference from #720? Is this basically a squash merge + some additional changes?

**Comment by jose-luis-rs** [comment]
The main difference is the use of Cluster instead of Hit and also R3BCalifaHitPar was renamed to R3BCalifaClusterPar.

**Comment by jose-luis-rs** [comment]
At the moment R3BCalifaHitPar (R3BCalifaClusterPar) is not used for analysis, so you don't need to change the names of your parameters. Really, it is not loaded by the container factory R3BCalifaContFact ...

**Comment by ryotani** [comment]
Ah, right. Thank you!

**Pull request merged**
