### PR TITLE
Fix frs & asyeos cmake errors

### PR DESCRIPTION
**Pull request by YanzhaoW**
Adapt FRS repository to CMake targets.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed the [pull request guidlines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and the [Git workflow](https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown)
* [x] Followed the [seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by YanzhaoW** [comment]
Hi @jose-luis-rs 

I submit [a PR](https://github.com/R3BRootGroup/frs/pull/31) in frs repo and it's required to pass the CI of this PR.

**Comment by YanzhaoW** [comment]
For the next time when both R3BRoot and subprojects needed to be changed, I think it's better to merge the PRs in the subprojects first and make sure the CIs are passed **here** before its merging.

**Comment by jose-luis-rs** [comment]
Thanks @YanzhaoW 
Now the code compiles with all the subprojects under FairRoot19.0.0, but it still fails with previous versions.

**Comment by YanzhaoW** [comment]
Ok, I will fix that in this PR.

**Comment by YanzhaoW** [comment]
Hi, @jose-luis-rs 

All tests in our CI (which uses FairRoot 18.8) passed. Are there any errors from your side?

**Comment by jose-luis-rs** [comment]
Many thanks @YanzhaoW

**Pull request merged**
