### PR TITLE
Added Print function

### PR DESCRIPTION
**Pull request by bheiss23**

### CODE REVIEW

**Comment by kresan** [comment]
all macros are now in the separate repository (https://github.com/R3BRootGroup/macros). Please do not commit them to R3BRoot

**Comment by bheiss23** [comment]
> all macros are now in the separate repository (https://github.com/R3BRootGroup/macros). Please do not commit them to R3BRoot

I did not know that, sorry. I removed it. Shall I squash the commits if the check is successful?

**Comment by kresan** [comment]
Could you please squash the commits

**Comment by bheiss23** [comment]
I thought I did previously. Guess I did something wrong. Is it alright now or do I need to do something else?

**Comment by kresan** [comment]
No, it is not alright. Now it says 5 commits (before was 3) and you did merge 2 of your own branches. This is how you squash:
git fetch mainrepo
git checkout BRANCH_NAME
git rebase -i mainrepo/dev
### edit text file: first commit "pick", all following "s"
### edit common commit message
git push -f origin BRANCH_NAME

**Comment by bheiss23** [comment]
All done

**Comment by kresan** [comment]
I do not know what goes wrong, but it is not rebased.
Please visit this link and check that your branch "dev2" is stemming from the latest commit in dev of the main repository. Before doing "git rebase" do not forget to "git fetch mainrepo"
Sorry, but I can not merge it in this way

**Comment by kresan** [comment]
The link [network](https://github.com/R3BRootGroup/R3BRoot/network)

**Pull request merged**
