### PR TITLE
Support for the new version of ext_data_setup() in R3BUcesbSource.

### PR DESCRIPTION
**Pull request by bl0x**
Ucesb has gained the ability to get more detailed information about how the mapping went during the setup(). This introduces also a change in the interface, so quick action is needed.

Also fix up a comment that was outdated.

### CODE REVIEW

**Comment by bl0x** [comment]
This change maintains backwards compatibility with older ucesb versions.
However, existing code may break with the new version of ucesb, if illegal mappings are performed which have so far not been discovered.

**Comment by bl0x** [comment]
Please merge as you like.

**Comment by kresan** [comment]
Please squash the commits

**Comment by bl0x** [comment]
Oops, yes. Done.

**Pull request merged**
