### PR TITLE
Add input parameter for Tamex channel and manual update

### PR DESCRIPTION
**Pull request by YanzhaoW**
1. The parameter of the Tamex channel can be setup through the user interface.
2. Update the manual.
---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed the [pull request guidlines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and the [Git workflow](https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown)
* [x] Followed the [seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by YanzhaoW** [comment]
Hi, @jose-luis-rs. It's now ready to be merged if no other problem.

**Comment by YanzhaoW** [comment]
Hi @jose-luis-rs . This PR is ready. Could you merge it?

**Comment by jose-luis-rs** [comment]
Hi @YanzhaoW 

Sorry, I hadn't seen this PR, just a simple question about the R3BNeulandDigitizer class. In the function R3BNeulandDigitizer::SetParContainers() the use of FairRunAna is mandatory, so this means that we cannot run the simulations + Digitizer tasks simultaneously. Can we make it optional?

In some cases, we want to produce "Point" and "Hit" data simultaneously without the use of extra macros.

**Comment by YanzhaoW** [comment]
Hi @jose-luis-rs 

I think this was added long time ago. The main reason of this is because the simulation of NeuLAND by FairRunSim is very very slow compared to FairRunAna. So it's strongly encourage to run the simulation only one time, and then change or check something using FairRuaAna. I would just keep making FairRunAna mandatory.

**Pull request merged**
