### PR TITLE
Upgrade CI container.

### PR DESCRIPTION
**Pull request by kresan**
FairSoft apr22
FairRoot v18.6.8

### CODE REVIEW

**Comment by kresan** [comment]
@jose-luis-rs This is what you have requested.

Compilation works, but the new tests are failing: [https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=361065](https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=361065)

Can you have a look at the failing tests? You can push to my branch directly, and this will trigger a new test.

**Comment by kresan** [comment]
I suggest to skip the `landreco` test. It is obsolete. @igasparic, can you check this?

**Comment by YanzhaoW** [comment]
@kresan tests in macro/r3b/land has been deprecated long time ago. Most of ( if not all ) tests concerning NeuLAND has been moved out from macro folder to /neuland folder. So, yes, skip the test of landreco.

**Comment by jose-luis-rs** [comment]
I have included your modifications on my PR #733, so I guess you can close this one.
Thanks

**Pull request closed without merging**
