### PR TITLE
[WIP] Migrate to GitHub-hosted runners

### PR DESCRIPTION
**Pull request by kresan**
Describe your proposal.

- Run R3BRoot CI on the GitHub-hosted Ubuntu 18.04
- Use FairSoft and FairRoot from CVMFS (versions will be updated soon)
- Only cvmfs package needs to be installed and configured - takes 1 min
- 2 cores are available per runner

Mention any issue this PR is resolved or is related to.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by inkdot7** [comment]
This sounds like a very good idea to try out!

Questions:
- Is it possible to limit the run-time of jobs?  (otherwise wild infinite-looping code may use up a lot of CI time) (I am in favour of running very many CI jobs, so this is more a sanity guard, should not be a hindrance)
- Is it possible to have CI jobs run automatically before making PRs?  (not really related to using ubuntu/cvmfs) but also very useful, c.f. #777)
- It seems the current commit runs fewer jobs (just 1) than other typical current PRs (4).  WIP?

**Comment by jose-luis-rs** [comment]
Thanks @kresan, I guess we can still use the CDash system to check the errors, warnings, ..., right?

**Comment by kresan** [comment]
- I do not know yet. We need to look in the workflow settings.
- You need to be a member of the R3BRootGroup to be able to run workflows. Should I add you that we can test this feature?
- Yes, WIP. I have adjusted title and label.

**Comment by kresan** [comment]
If one runs ./Dart.sh inside of the workflow, then the results will be published to CDash. That did not change.

For the moment as WIP I use cmake / make, without ctest.

**Comment by inkdot7** [comment]
@kresan yes, please add me, then I'll see if I can hit the buttons to run some job.

**Comment by inkdot7** [comment]
After a job finished, I saw the following:
```
CI C17++: .github#L1
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```
Is there a particular reason to use the 18.04 environment?

Also, just building R3BRoot took about 14 minutes.  That is a long time to wait.  I would advocate to use wider machines, at least 4 cores.

**Comment by kresan** [comment]
Currently, fairsoft.gsi.de supports only Ubuntu 18.04. I will ask Florian to build FairSoft and FairRoot for 22.04. I think there was simply no request before.

**Comment by inkdot7** [comment]
What are the current outstanding issues with this PR?

**Review by jose-luis-rs — APPROVED** [review]

**Comment by kresan** [comment]
Due to time constrains I can not continue working in this direction. @jose-luis-rs how do we proceed? Should we merge and somebody else develops on top of what is in this PR?

**Comment by jose-luis-rs** [comment]
> Due to time constrains I can not continue working in this direction. @jose-luis-rs how do we proceed? Should we merge and somebody else develops on top of what is in this PR?

Hi, I have it running for other repositories, but we will need ubuntu-22-04 with fairsoft-nov22p1 and fairroot 18.8.X, is this possible?
I have a similar problem due to other projects.

**Comment by YanzhaoW** [comment]
@kresan @jose-luis-rs I could do this since I have already made github-hosted server for clang-tidy (with successful compilation). 

But I will build upon my clang-tidy workflow, which is actually partly based on this PR.

**Comment by jose-luis-rs** [comment]
> @kresan @jose-luis-rs I could do this since I have already made github-hosted server for clang-tidy (with successful compilation).
> 
> But I will build upon my clang-tidy workflow, which is actually partly based on this PR.

If you have time I don't see any problem.
Thanks in advance

**Comment by kresan** [comment]
@jose-luis-rs @YanzhaoW There are new installations for Ubuntu 22.04 available now:

`/cvmfs/fairsoft.gsi.de/ubuntu2204`

@YanzhaoW Thanks for picking up on this.

**Comment by jose-luis-rs** [comment]
> @jose-luis-rs @YanzhaoW There are new installations for Ubuntu 22.04 available now:
> 
> `/cvmfs/fairsoft.gsi.de/ubuntu2204`
> 
> @YanzhaoW Thanks for picking up on this.

Thank you @kresan!

**Comment by YanzhaoW** [comment]
> 

@kresan But we should keep using debian 10, right? It's the same system as we use in the lxir server.

**Comment by jose-luis-rs** [comment]
> > 
> 
> @kresan But we should keep using debian 10, right? It's the same system as we use in the lxir server.

I will have both, Ubuntu 22.04 and debian10, running for sofia and asyeos

**Comment by YanzhaoW** [comment]
> > @kresan But we should keep using debian 10, right? It's the same system as we use in the lxir server.
> 
> I will have both, Ubuntu 22.04 and debian10, running for sofia and asyeos

Ok, sure.

**Comment by jose-luis-rs** [comment]
Solved with #840

**Pull request closed without merging**
