### PR TITLE
add comments in R3BMusliMapped2Cal

### PR DESCRIPTION
**Pull request by audreychatillon**
clang-format

change some variable names to get difference between time and drift time

Describe your proposal.

Mention any issue this PR is resolved or is related to.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed the [pull request guidlines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and the [Git workflow](https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown)
* [x] Followed the [seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by ryotani** [comment]
Hi just a quick question. Did you plan to use musli firmware for the experiments in February? We're thinking of making online spectra classes and wondering if we should use musli or twim classes.

**Comment by audreychatillon** [comment]
with light ions we should use musli firmware.
In principle, a lot (parameters and online) was already developed for the
Anna and Olivier experiments in 2022.
I am looking at the code now and try to add few comments.


Le ven. 2 févr. 2024 à 17:49, Ryo Taniuchi ***@***.***> a
écrit :

**Comment by audreychatillon** [comment]
I have already prepared the FrsSci versus Musli
I am not sure this is really useful finally.
For Marina experiment, there is no FrsSci at Cave C.
So the AoQ should be done using LOS as stop.

@Ryo Taniuchi ***@***.***> if you want to check the code, to
see what is already available.
Maybe for Marina experiment, we will need to use sci2, los and musli.
In that case, we will have to modify the mapping in upexps.
The latter should anyhow been modified, since there is not the same number
of of scintiallators between s118 and s091

**Comment by audreychatillon** [comment]
at least it will be useful for C beam at the begining of the Roman´s
experiment, while tuning the FRS.

**Comment by jose-luis-rs** [comment]
We can add LOS later, can I merge this?

**Comment by audreychatillon** [comment]
for me, yes !

**Pull request merged**
