### PR TITLE
[merge ready] Clang tidy: fixed some warnings, replaced C-style casts. 

### PR DESCRIPTION
**Pull request by klenze**
Should CI like this commit, please consider merging it.

### CODE REVIEW

**Comment by klenze** [comment]
One of the problems clang-tidy warned me about is that
```virtual Bool_t R3BReader::Read()```
conflicts with
```virtual Int_t TObject::Read(const char *name);```

As it is bad style to have two methods with equal names but completely different meaning, I changed the R3BReader::Read to R3BReader::R3BRead. 

If this PR gets merged, Sofia will have to fix this in https://github.com/R3BRootGroup/sofia/blob/master/sofsource/R3BSofAtReader.h

**Comment by jose-luis-rs** [comment]
Thanks @klenze , please, could you rebase the dev branch and apply the same modifications on the sofia repository?

**Comment by jose-luis-rs** [comment]
Please, rebase the dev branch to update the CIs

**Comment by klenze** [comment]
[Sofia PR](https://github.com/R3BRootGroup/sofia/pull/302).

**Pull request merged**
