### PR TITLE
Update hit s2

### PR DESCRIPTION
**Pull request by nmozumdar**
Update hit selection in S2

### CODE REVIEW

**Comment by ryotani** [comment]
Although I have no time to follow carefully the logic, as long as I read all changes once, I think the update looks fine. 
One comment:
You defined COINC_WINDOW for selecting a "good hit" within one plastic detector to have a reasonable time difference between left and right PMTs. Can you make it a parameter at least accessible from a mutator function as SetCoincWindow(Float_t tdiff), or even set from the parameter class?

**Comment by nmozumdar** [comment]
Yes I can definitely implement this, I guess using a function is easier and makes it more accessible. Thanks a lot for the comments.

**Comment by ryotani** [comment]
If you make an update, then you just push the new commit to your branch, then it should automatically update the pull request. It's not urgent but mentioning this just in case if you struggle how to deal with github.

**Comment by nmozumdar** [comment]
Thanks a lot for the advice, I am a complete novice to git hub so any help is appreciated. I have made the changes

Btw I needed to talk to you about s2 calibration and hit selection  using s2-los, I am running some checks now and i will send you a mail shortly after

**Comment by ryotani** [comment]
Yes, feel free to send me an email. Or we can discuss it in the issues section of this github repository.

**Pull request merged**
