### PR TITLE
Update to ensure compatibility with the NeuLAND DNN algoritm (sep. re…

### PR DESCRIPTION
**Pull request by ChristiaanDoumaDNN**
Please consider these changes to make R3BRoot compatible with the NeuLAND_DNN repository.

### CODE REVIEW

**Comment by kresan** [comment]
you made NeuLAND_DNN package as required. Please make it optional. You can look up how it is solved for sofia.

**Comment by ChristiaanDoumaDNN** [comment]
I made the changes.

Op vr 20 mrt. 2020 om 11:51 schreef Dmytro Kresan <notifications@github.com

**Comment by janmayer** [comment]
One thing: The new detector entries are prefixed with CAD - that probably stands for your name, but it can be confused with Computer Aided Design. How about DNN?

**Comment by ChristiaanDoumaDNN** [comment]
It would be a dangerous operation to change that class prefix everywhere. Or do just mean changing the enumerations in the detector list?

**Comment by janmayer** [comment]
> Or do just mean changing the enumerations in the detector list?

Yes, I mean the entries in `r3bdata/R3BDetectorList.h`

**Comment by ChristiaanDoumaDNN** [comment]
I have made the change.

**Comment by kresan** [comment]
all fine. one last thing: please squash the commits into a single one as described in the git workflow documentation

**Comment by kresan** [comment]
closing as duplicate of #340

**Pull request closed without merging**
