### PR TITLE
R3BEventHeader in Hit level.

### PR DESCRIPTION
**Pull request by ashtonfalduto**
sfib classes added
R3BEventHeader Hit level added

### CODE REVIEW

**Comment by kresan** [comment]
You need to fix code-formatting issues using clang-format and afterwards force-push again.

**Comment by kresan** [comment]
GitHub CI is now set up properly. Please rebase to run the tests.

**Comment by jose-luis-rs** [comment]
Hello

There are problems with the tofd data structure ext_h101_tofd.h, trigger info is missing. I will try to solve the problem!

**Comment by jose-luis-rs** [comment]
This PR was already included in my PR #398, so it can be closed.

**Pull request closed without merging**
